#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibgen(supremum):
	""" 
	a generator to return fibonacci numbers < supremum
	"""
	n2 = 0
	n1 = 1
	n = n2 + n1
#	yield n2
#	yield n1
	yield n
	while True:
		n2 = n1
		n1 = n
		n = n2 + n1
		if n < supremum:
			yield n
		else:
			 break

sum = 0
for i in fibgen(4000000):
	if i%2==0:
		sum += i
print sum
